CREATE TABLE invoices (
    id SERIAL PRIMARY KEY,
    operation_type VARCHAR(255) NOT NULL,
    number VARCHAR(50) NOT NULL,         
    date_from DATE NOT NULL,             
    shipper VARCHAR(255) NOT NULL,       
    shipper_warehouse VARCHAR(255) NOT NULL, 
    receiver VARCHAR(255) NOT NULL,     
    receiver_warehouse VARCHAR(255) NOT NULL, 
    reason VARCHAR(255) NOT NULL,       
    reason_details VARCHAR(255),         
    reason_date DATE,                   
    reason_number VARCHAR(50),          
 
    rao_chief VARCHAR(255),
    rao_chief_details VARCHAR(255),
    rao_chief_signature VARCHAR(255),
    rao_chief_stamp VARCHAR(255),
    fes_chief VARCHAR(255),
    fes_chief_details VARCHAR(255),
    fes_chief_signature VARCHAR(255),
    fes_chief_stamp VARCHAR(255),
    rao_clerk VARCHAR(255),
    rao_clerk_details VARCHAR(255),
    rao_clerk_signature VARCHAR(255),
    rao_clerk_stamp VARCHAR(255),
    warehouse_chief VARCHAR(255),
    warehouse_chief_details VARCHAR(255),
    warehouse_chief_signature VARCHAR(255),
    receiver_signature VARCHAR(255),
    receiver_details VARCHAR(255)
);