export type Item = {
  id: string;
  name: string;
  number: string;
  quantity: string;
  price: string;
};

export const fakeData: Item[] = [
//   {
//     id: '9s41rp',
//     name: 'Kelvin',
//     number: 'Langosh',
//     quantity: 'Jerod14@hotmail.com',
//     price: 'Ohio',
//   },
//   {
//     id: '08m6rx',
//     name: 'Molly',
//     number: 'Purdy',
//     quantity: 'Hugh.Dach79@hotmail.com',
//     price: 'Rhode Island',
//   },
//   {
//     id: '5ymtrc',
//     name: 'Henry',
//     number: 'Lynch',
//     quantity: 'Camden.Macejkovic@yahoo.com',
//     price: 'California',
//   },
//   {
//     id: 'ek5b97',
//     name: 'Glenda',
//     number: 'Douglas',
//     quantity: 'Eric0@yahoo.com',
//     price: 'Montana',
//   },
//   {
//     id: 'xxtydd',
//     name: 'Leone',
//     number: 'Williamson',
//     quantity: 'Ericka_Mueller52@yahoo.com',
//     price: 'Colorado',
//   },
//   {
//     id: 'wzxj9m',
//     name: 'Mckenna',
//     number: 'Friesen',
//     quantity: 'Veda_Feeney@yahoo.com',
//     price: 'New York',
//   },
//   {
//     id: '21dwtz',
//     name: 'Wyman',
//     number: 'Jast',
//     quantity: 'Melvin.Pacocha@yahoo.com',
//     price: 'Montana',
//   },
//   {
//     id: 'o8oe4k',
//     name: 'Janick',
//     number: 'Willms',
//     quantity: 'Delfina12@gmail.com',
//     price: 'Nebraska',
//   },
];

//50 us prices array
export const listNames = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
  'Puerto Rico',
];
